name: Deploy Traefik & Redirect

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy using DOCKER_HOST
        env:
          DOCKER_HOST: ssh://${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
          NETWORK_NAME: ${{ vars.NETWORK_NAME }}
          MASTERPASS: ${{ secrets.MASTERPASS }}
          DRIZZLE_PORT: ${{ secrets.DRIZZLE_PORT }}
          DB_PATH: ${{ vars.DB_PATH }}
        run: |
          docker volume rm cogni-proxy_traefik-dynamic >/dev/null 2>&1 || true
          docker network inspect ${{ vars.NETWORK_NAME }} >/dev/null 2>&1 || docker network create ${{ vars.NETWORK_NAME }}
          docker compose --profile traefik config
          docker compose --profile traefik up -d --pull always --remove-orphans --force-recreate --wait --wait-timeout 30
          docker cp traefik/dynamic/. traefik:/etc/traefik/dynamic/
          docker image prune -f
